# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-08 18:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 8, 18, 18, 56, 484618, tzinfo=utc)),
        ),
    ]
