# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-11 11:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200608_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 11, 11, 46, 17, 85183, tzinfo=utc)),
        ),
    ]
